# Generated by Django 3.2 on 2022-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_plan', '0002_auto_20220415_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='offered_answer',
            field=models.ManyToManyField(blank=True, to='business_plan.OfferedAnswer', verbose_name='Offered Answer'),
        ),
    ]
