# Generated by Django 3.2 on 2022-04-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_plan', '0004_auto_20220415_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_postive_int',
            new_name='answer_positive_int',
        ),
    ]
